/** Curated creative headshots for the homepage Talent Navigator preview. */
export const CREATIVE_HEADSHOT_PATHS = [
  "/marketing/creative-headshots/01.jpg",
  "/marketing/creative-headshots/02.jpg",
  "/marketing/creative-headshots/03.jpg",
  "/marketing/creative-headshots/04.jpg",
  "/marketing/creative-headshots/05.jpg",
  "/marketing/creative-headshots/06.jpg",
  "/marketing/creative-headshots/07.jpg",
  "/marketing/creative-headshots/08.jpg",
  "/marketing/creative-headshots/09.jpg",
  "/marketing/creative-headshots/10.jpg",
  "/marketing/creative-headshots/11.jpg",
  "/marketing/creative-headshots/12.jpg",
  "/marketing/creative-headshots/13.jpg",
  "/marketing/creative-headshots/14.jpg",
  "/marketing/creative-headshots/15.jpg",
  "/marketing/creative-headshots/16.jpg",
  "/marketing/creative-headshots/17.jpg",
  "/marketing/creative-headshots/18.jpg",
  "/marketing/creative-headshots/19.jpg",
  "/marketing/creative-headshots/20.jpg",
  "/marketing/creative-headshots/21.jpg",
  "/marketing/creative-headshots/22.jpg",
  "/marketing/creative-headshots/23.jpg",
  "/marketing/creative-headshots/24.jpg",
] as const;
