import { portraitWallImages } from "@/lib/mock-data";

import {
  DEFAULT_NAVIGATOR_FILTER_OPTIONS,
  ETHNICITY_OPTIONS,
  GENDER_OPTIONS,
  GENRE_OPTIONS,
  HEIGHT_OPTIONS,
  REPRESENTATION_OPTIONS,
  UNION_STATUS_OPTIONS,
} from "./filter-options";
import type { Talent } from "./types";

function img(index: number) {
  return portraitWallImages[index % portraitWallImages.length];
}

const BASE_TALENT: Omit<Talent, "id" | "slug" | "name" | "imageUrl">[] = [
  {
    pronouns: "she/her",
    location: "Los Angeles, CA",
    agency: "Bloc LA",
    styles: ["Commercial", "Hip-Hop"],
    height: "5'7\"",
    availability: "Available this month",
    unionStatus: "SAG-AFTRA",
    experience: "Professional",
    credits: ["Nike Campaign", "Super Bowl Halftime"],
    represented: true,
    gender: "Female",
    ethnicity: "Asian American",
    recentlyActive: true,
    recommended: true,
  },
  {
    pronouns: "he/him",
    location: "New York, NY",
    agency: "Movement House",
    styles: ["Contemporary", "Jazz"],
    height: "6'0\"",
    availability: "Available next month",
    unionStatus: "Non-union",
    experience: "Emerging",
    credits: ["Broadway Workshop", "Regional Tour"],
    represented: true,
    gender: "Male",
    ethnicity: "Black",
    newToMotiion: true,
    recommended: true,
  },
  {
    pronouns: "they/them",
    location: "Atlanta, GA",
    agency: "Clear Talent",
    styles: ["Hip-Hop", "Commercial"],
    height: "5'9\"",
    availability: "Available this month",
    unionStatus: "SAG-AFTRA",
    experience: "Professional",
    credits: ["Music Video — Drake", "World Tour"],
    represented: true,
    gender: "Non-binary",
    ethnicity: "Latino",
    recentlyActive: true,
  },
  {
    pronouns: "she/her",
    location: "Los Angeles, CA",
    agency: "MSA",
    styles: ["Commercial", "Contemporary"],
    height: "5'5\"",
    availability: "Booked — opens April",
    unionStatus: "SAG-AFTRA",
    experience: "Professional",
    credits: ["Apple Keynote", "Brand Campaign"],
    represented: true,
    gender: "Female",
    ethnicity: "White",
    recommended: true,
  },
  {
    pronouns: "he/him",
    location: "Chicago, IL",
    agency: "Independent",
    styles: ["Ballet", "Contemporary"],
    height: "5'11\"",
    availability: "Available this month",
    unionStatus: "Non-union",
    experience: "Emerging",
    credits: ["Joffrey Apprenticeship"],
    represented: false,
    gender: "Male",
    ethnicity: "White",
    newToMotiion: true,
  },
  {
    pronouns: "she/her",
    location: "New York, NY",
    agency: "Bloc LA",
    styles: ["Hip-Hop", "Heels"],
    height: "5'6\"",
    availability: "Available this month",
    unionStatus: "SAG-AFTRA",
    experience: "Professional",
    credits: ["MTV Awards", "Commercial Reel"],
    represented: true,
    gender: "Female",
    ethnicity: "Black",
    recentlyActive: true,
    recommended: true,
  },
  {
    pronouns: "he/him",
    location: "Miami, FL",
    agency: "Movement House",
    styles: ["Latin", "Commercial"],
    height: "5'10\"",
    availability: "Available next month",
    unionStatus: "Non-union",
    experience: "Professional",
    credits: ["Latin Grammy Performance"],
    represented: true,
    gender: "Male",
    ethnicity: "Latino",
  },
  {
    pronouns: "she/her",
    location: "Los Angeles, CA",
    agency: "Clear Talent",
    styles: ["Contemporary", "Jazz"],
    height: "5'8\"",
    availability: "Available this month",
    unionStatus: "SAG-AFTRA",
    experience: "Professional",
    credits: ["So You Think You Can Dance", "Tour"],
    represented: true,
    gender: "Female",
    ethnicity: "Mixed",
    recentlyActive: true,
  },
  {
    pronouns: "he/him",
    location: "New York, NY",
    agency: "MSA",
    styles: ["Commercial", "Hip-Hop"],
    height: "6'1\"",
    availability: "Available this month",
    unionStatus: "SAG-AFTRA",
    experience: "Professional",
    credits: ["Fashion Week", "Editorial"],
    represented: true,
    gender: "Male",
    ethnicity: "Asian American",
    recommended: true,
  },
  {
    pronouns: "she/her",
    location: "Atlanta, GA",
    agency: "Independent",
    styles: ["Hip-Hop", "Commercial"],
    height: "5'4\"",
    availability: "Available this month",
    unionStatus: "Non-union",
    experience: "Emerging",
    credits: ["Local Commercial", "Music Video"],
    represented: false,
    gender: "Female",
    ethnicity: "Black",
    newToMotiion: true,
  },
  {
    pronouns: "he/him",
    location: "Los Angeles, CA",
    agency: "Bloc LA",
    styles: ["Contemporary", "Commercial"],
    height: "5'9\"",
    availability: "Available next month",
    unionStatus: "SAG-AFTRA",
    experience: "Professional",
    credits: ["Film — Indie Feature", "Commercial Pool"],
    represented: true,
    gender: "Male",
    ethnicity: "White",
    recentlyActive: true,
  },
  {
    pronouns: "she/her",
    location: "Chicago, IL",
    agency: "Movement House",
    styles: ["Jazz", "Commercial"],
    height: "5'7\"",
    availability: "Available this month",
    unionStatus: "Non-union",
    experience: "Emerging",
    credits: ["Chicago Dance Festival"],
    represented: true,
    gender: "Female",
    ethnicity: "Latino",
  },
  {
    pronouns: "they/them",
    location: "New York, NY",
    agency: "Clear Talent",
    styles: ["Contemporary", "Ballet"],
    height: "5'10\"",
    availability: "Available this month",
    unionStatus: "SAG-AFTRA",
    experience: "Professional",
    credits: ["Alvin Ailey Workshop", "Regional Ballet"],
    represented: true,
    gender: "Non-binary",
    ethnicity: "Black",
    recommended: true,
  },
  {
    pronouns: "she/her",
    location: "Miami, FL",
    agency: "MSA",
    styles: ["Latin", "Heels"],
    height: "5'5\"",
    availability: "Available this month",
    unionStatus: "Non-union",
    experience: "Professional",
    credits: ["Latin Tour", "Brand Ambassador"],
    represented: true,
    gender: "Female",
    ethnicity: "Latino",
    recentlyActive: true,
  },
  {
    pronouns: "he/him",
    location: "Los Angeles, CA",
    agency: "Independent",
    styles: ["Hip-Hop", "Commercial"],
    height: "6'2\"",
    availability: "Available this month",
    unionStatus: "Non-union",
    experience: "Emerging",
    credits: ["Street Dance Battle", "Reels"],
    represented: false,
    gender: "Male",
    ethnicity: "Black",
    newToMotiion: true,
  },
  {
    pronouns: "she/her",
    location: "New York, NY",
    agency: "Bloc LA",
    styles: ["Commercial", "Contemporary"],
    height: "5'6\"",
    availability: "Booked — opens May",
    unionStatus: "SAG-AFTRA",
    experience: "Professional",
    credits: ["Netflix Series", "Tour"],
    represented: true,
    gender: "Female",
    ethnicity: "Asian American",
  },
  {
    pronouns: "he/him",
    location: "Atlanta, GA",
    agency: "Movement House",
    styles: ["Hip-Hop", "Commercial"],
    height: "5'11\"",
    availability: "Available this month",
    unionStatus: "SAG-AFTRA",
    experience: "Professional",
    credits: ["Award Show", "Brand Campaign"],
    represented: true,
    gender: "Male",
    ethnicity: "Black",
    recentlyActive: true,
    recommended: true,
  },
  {
    pronouns: "she/her",
    location: "Los Angeles, CA",
    agency: "Clear Talent",
    styles: ["Heels", "Commercial"],
    height: "5'3\"",
    availability: "Available this month",
    unionStatus: "Non-union",
    experience: "Emerging",
    credits: ["Heels Intensive", "Music Video"],
    represented: true,
    gender: "Female",
    ethnicity: "Mixed",
    newToMotiion: true,
  },
  {
    pronouns: "he/him",
    location: "Chicago, IL",
    agency: "MSA",
    styles: ["Ballet", "Contemporary"],
    height: "6'0\"",
    availability: "Available next month",
    unionStatus: "Non-union",
    experience: "Professional",
    credits: ["Joffrey", "Regional Company"],
    represented: true,
    gender: "Male",
    ethnicity: "White",
  },
  {
    pronouns: "she/her",
    location: "New York, NY",
    agency: "Independent",
    styles: ["Jazz", "Contemporary"],
    height: "5'8\"",
    availability: "Available this month",
    unionStatus: "SAG-AFTRA",
    experience: "Professional",
    credits: ["Broadway Ensemble", "Workshop"],
    represented: false,
    gender: "Female",
    ethnicity: "White",
    recentlyActive: true,
  },
];

const FIRST_NAMES = [
  "Maya",
  "Jordan",
  "Sofia",
  "Ethan",
  "Ari",
  "Niko",
  "Zara",
  "Kai",
  "Lena",
  "Marcus",
  "Isabella",
  "Devon",
  "Amara",
  "Luca",
  "Priya",
  "Tyler",
  "Naomi",
  "Andre",
  "Chloe",
  "Diego",
];

const LAST_NAMES = [
  "Chen",
  "Ellis",
  "Reyes",
  "Park",
  "Miles",
  "Lane",
  "Okonkwo",
  "Santos",
  "Kim",
  "Brooks",
  "Torres",
  "Nguyen",
  "Williams",
  "Patel",
  "Johnson",
  "Rivera",
  "Foster",
  "Davis",
  "Martinez",
  "Lee",
];

export const mockNavigatorTalent: Talent[] = BASE_TALENT.map((base, index) => {
  const first = FIRST_NAMES[index];
  const last = LAST_NAMES[index];
  const slug = `${first.toLowerCase()}-${last.toLowerCase()}`;

  return {
    id: `nav-talent-${index + 1}`,
    slug,
    name: `${first} ${last}`,
    imageUrl: img(index),
    ...base,
  };
});

export const FILTER_OPTIONS = {
  locations: DEFAULT_NAVIGATOR_FILTER_OPTIONS.locations,
  agencies: DEFAULT_NAVIGATOR_FILTER_OPTIONS.agencies,
  styles: [...GENRE_OPTIONS],
  representation: [...REPRESENTATION_OPTIONS],
  gender: [...GENDER_OPTIONS],
  ethnicity: [...ETHNICITY_OPTIONS],
  height: [...HEIGHT_OPTIONS],
  availability: ["Available this month", "Available next month", "Booked — opens April", "Booked — opens May"],
  unionStatus: [...UNION_STATUS_OPTIONS],
  experience: ["Emerging", "Professional"],
} as const;

export const SAVED_SEARCHES = [
  {
    id: "la-commercial",
    label: "LA Commercial",
    filters: { location: "Los Angeles", style: "Commercial" },
  },
  {
    id: "ny-contemporary",
    label: "NY Contemporary",
    filters: { location: "New York", style: "Contemporary" },
  },
  {
    id: "available-now",
    label: "Available This Month",
    filters: { availability: "Available this month" },
  },
  {
    id: "represented-hiphop",
    label: "Represented Hip-Hop",
    filters: { representation: "Represented", style: "Hip-Hop" },
  },
] as const satisfies readonly import("./types").SavedSearch[];
